version: 0.0
os: linux
files:
  - source: project-0.1.8.jar
    destination: /java-app/
hooks:
  ApplicationStop:
    - location: scripts/application_stop.sh
      runas: root
  BeforeInstall:
    - location: scripts/before_install.sh
      runas: root
  ApplicationStart:
    - location: scripts/application_start.sh
      runas: root
  